name: duxt_docs
description: Official Duxt documentation site
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  jaspr: ^0.22.1
  jaspr_router: ^0.8.1
  jaspr_content: ^0.4.5
  duxt: ^0.6.1
  duxt_ui: ^0.2.0
  duxt_icons: ^0.1.0
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.4.8
  jaspr_builder: ^0.22.1
  lints: ^6.0.0

jaspr:
  mode: static
