name: duxtdocs
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.1
  jaspr_content: ^0.4.5
  jaspr_router: ^0.8.1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.8
  jaspr_builder: ^0.22.1
  jaspr_tailwind: ^0.3.6
  lints: ^6.0.0

jaspr:
  mode: static
